### ISSUE TITLE
Another possible theme for Plentico - fitness

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/plenti-fitlife#1]
Hi @jimafisk 
How are you going?

While taking a short break from working on the Educenter theme, I came across another nice template and thought I would tackle it. It came together rather quickly maybe because I am getting the hang of working with Plenti sites now. Anyway, this template is called [Fitlife](https://codewithsadee.github.io/fitlife/) and the source code is on [Github](https://github.com/codewithsadee/fitlife) and comes from a developer by the name Sadee of codewithsadee. (He has some more nice website designs to explore too) It is free to use and does not contain any licences.  It looks clean with some nice CSS animations.
Please have a look and see what you think. 

Some thoughts going forward with this one is possibly adding blog pages because the developer has included a 'News feed/blog' in the index but without any pages. Also could add a Contact Us page too. :)

Best regards,
Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 

A couple of code matters with this theme.
1. I saw the following [Javascript code](https://github.com/codewithsadee/fitlife/blob/master/assets/js/script.js#L9-L17) in his file and wasn't sure what it did...and haven't included it..
```javascript
/**
 * add event on element
 */

const addEventOnElem = function (elem, type, callback) {
  if (elem.length > 1) {
    for (let i = 0; i < elem.length; i++) {
      elem[i].addEventListener(type, callback);
    }
  } else {
    elem.addEventListener(type, callback);
  }
}
```
2. I am not seeing the scroll to top button that should appear down on the right side as you scroll down the page. So not sure why that isn't visible.

Ben

**Comment by jimafisk** [comment]
@jamestagal you're building out themes faster than I can review them! It's fun to see how fast you're progressing, keep crushing it :).

I started up the theme you created locally and it looks awesome already. So I created a release repo for it https://github.com/plenti-themes/fitlife and added you as a collaborator. I've also added a theme page to the website for it: https://plenti.co/themes/fitlife and deployed a demo site to GitHub pages: https://plenti-themes.github.io/fitlife/

**Comment by jimafisk** [comment]
I'm not sure exactly what that JS code is doing by looking at it. If it's not breaking anything you care about, I'd say you're fine omitting it for now :). If you find you're missing something important, we can take another look.

You basically had the scroll to top logic correct. I just swapped out the html to match the demo site.

So it was:
```svelte
<div class="data-back-top-btn {y > 100 ? ' active' : ''}">
```

Now it's:

```svelte
<a href="#top" class="back-top-btn{y > 100 ? ' active' : ''}" aria-label="back to top" data-back-top-btn="">
  <ion-icon name="caret-up-sharp" aria-hidden="true" role="img" class="md hydrated"></ion-icon>
</a>
```

**Comment by jamestagal** [comment]
Hi @jimafisk 
No worries...I have plenti more themes in the pipeline to do next! (Do you like my pun on word Plenti/plenty?)
That reminds me, does 'Plenti' have a meaning? 
Also I see that you might have rebranded? from Jantcu -> [Causeworks](https://causeworks.com/)? I like your site, business model and target cliental. :) You are a small team (you and Stephanie) but I'm sure you are crushing it! Also I like that you are the 'A' team without saying it directly! 
Just an aside, I was profiled in a recent blog post with the TEL Edvisors (Technology Enhanced Learning Educator Advisors) network and I mentioned the Plenti project. Read [here](https://teledvisors.net/blog/?na=view&id=3). 

Thanks for fixing the scroll. :) 

Actually I do see a small issue: The hamburger menu in the nav when on smaller screens isn't working. I remember I added the same code/logic to the ```nav.svelte``` [file ](https://github.com/plenti-themes/fitlife/blob/main/layouts/global/nav.svelte)as we did for the previous theme but maybe I didn't do it correctly. Pls have a look when you get a chance. Here are the lines ```script.js``` [file](https://github.com/codewithsadee/fitlife/blob/1de9e49f155d8f55507f592581fa893aa53b6b14/assets/js/script.js#L25-L35) from the original.

Ben

**Comment by jimafisk** [comment]
> I have plenti more themes in the pipeline to do next!

:laughing: 

> Also I see that you might have rebranded?

Working on it! It's been a busy year so it's taking longer than I wanted, but hopefully we'll officially cutover to Causeworks soon!

> I was profiled in a recent blog post with the TEL Edvisors (Technology Enhanced Learning Educator Advisors) network and I mentioned the Plenti project.

Congrats that so cool!! Wow thank you for the mention :blush: 

> The hamburger menu in the nav when on smaller screens isn't working

I don't have time tonight, but I'll try to take a look soon. If you don't hear from me please feel free to ping me again because sometimes these things fall off my radar. Thanks Ben!

**Comment by jamestagal** [comment]
Hi @jimafisk 

No worries. When you have time, could you please give priority to this [issue](https://github.com/jamestagal/edtechdesigner/issues/33) ... ```error with layouts_content_404_svelte``` I am stuck with an issue on my site. 
Also I posted in a previous thread to ask Roberto about writing a [Netlify function](https://github.com/jamestagal/edtechdesigner/issues/17) back in July but he hasn't replied.  I hope he is ok.

Thanks Jim

**Comment by jamestagal** [comment]
Hi @jimafisk 
How are you going?
I was able to fix the nav toggle on mobile issue listed above so it is working as expected now. :) I just had the code in the wrong spots again! So I pushed the changes to the theme. See link below.
See here  https://github.com/plenti-themes/fitlife/commit/69a6b0751d01b8aa58c612902d30b97a7c71a389
I will close this issue now.

Cheers,
Ben

**Comment by jimafisk** [comment]
Awesome, nice work @jamestagal!!
